/** Documented design token names for the SignalCare design system. */
export const DS_COLOR_TOKENS = [
  'surface-base',
  'surface-muted',
  'surface-subtle',
  'surface-inverse',
  'surface-app',
  'text-primary',
  'text-primary-header',
  'text-primary-assigned',
  'text-secondary',
  'text-placeholder',
  'text-disabled',
  'text-inverse',
  'border-subtle',
  'border-default',
  'border-brand',
  'border-strong',
  'interactive-default',
  'interactive-subtle-bg',
  'interactive-selected-bg',
  'alert-danger-icon',
  'alert-danger-bg',
  'alert-danger-border',
  'alert-danger-text',
  'alert-warning-icon',
  'alert-warning-bg',
  'alert-warning-border',
  'alert-warning-text',
  'alert-success-border',
  'alert-success-bg',
  'alert-success-text',
] as const;

export const DS_SPACING_TOKENS = [
  'space-1',
  'space-2',
  'space-3',
  'space-4',
  'space-5',
  'space-6',
  'space-8',
] as const;

export const DS_RADIUS_TOKENS = ['radius-xs', 'radius-md', 'radius-lg', 'radius-pill'] as const;

export const DS_SHADOW_TOKENS = ['shadow-focus', 'shadow-card'] as const;

export const DS_ICON_SIZE_TOKENS = [
  'icon-size-xs',
  'icon-size-sm',
  'icon-size-md',
  'icon-size-lg',
  'icon-size-xl',
  'icon-size-empty',
] as const;

export const DS_TYPOGRAPHY_TOKENS = [
  'font-family',
  'font-size-overline',
  'font-size-body-sm',
  'font-size-body',
  'font-size-body-lg',
  'font-size-heading-2',
  'font-size-heading-1',
  'font-size-heading-4',
  'font-size-heading-3',
  'font-size-display-3',
  'font-weight-regular',
  'font-weight-medium',
  'font-weight-semibold',
  'font-weight-bold',
  'line-height-tight',
  'line-height-normal',
  'line-height-body',
  'line-height-relaxed',
  'line-height-row',
  'line-height-score',
  'line-height-header',
  'line-height-display',
  'line-height-empty',
  'line-height-overline',
  'line-height-step',
  'tracking-label',
  'tracking-heading-2',
  'tracking-score',
  'tracking-heading-1',
] as const;

export const DS_LAYOUT_TOKENS = [
  'sidebar-width',
  'header-height',
  'shell-nav-padding',
  'shell-nav-gap',
  'shell-nav-section-gap',
  'shell-nav-button-width',
  'shell-nav-button-padding',
  'shell-nav-icon-label-gap',
  'shell-header-padding-x',
  'shell-header-padding-y',
  'shell-header-icon-gap',
  'shell-menu-padding-x',
  'shell-menu-padding-y',
  'action-bar-padding-y',
  'action-bar-padding-x',
  'card-padding',
  'timeline-step-size',
  'queue-filter-bar-height',
  'queue-filter-control-height',
  'queue-search-width',
  'queue-dropdown-width',
  'queue-filter-gap',
  'queue-filter-padding-x',
  'queue-filter-padding-y',
  'queue-clear-all-right',
  'queue-clear-all-height',
  'queue-section-header-height',
  'queue-section-header-padding-x',
  'queue-section-header-padding-y',
  'queue-severity-bar-width',
  'queue-row-details-gap',
  'queue-row-leading-gap',
  'queue-row-meta-gap',
  'split-queue-min-width',
  'split-queue-max-width',
  'split-queue-width-percent',
] as const;
